// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ef02a61b-a7c2-46fc-883d-923a3493080c";

// estas tres constantes no cambian en la versión en linea, ya que se asignan por medio de variables desde otro archivo llamado secret
const char SSID[]               = 'PATHRY';    // Network SSID (name)
const char PASS[]               = 'xfMC2J9w5K';    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = 'HF2QHG676C00SBHKKFHQ';    // Secret device password

void onLuzChange();

CloudLight luz;
CloudTemperatureSensor temperatura;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(luz, READWRITE, ON_CHANGE, onLuzChange);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
